version: '3.2'
services:
  datacatalogue_backend:
    build: ''
    image: spring-boot-backend
    ports:
      - 8086
    depends_on:
      - datacatalogue_postgres
    links:
      - datacatalogue_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://datacatalogue_postgres:5432/datacatalog
      - spring.datasource.username=andy
      - spring.datasource.password=password
      - keycloak.client.clientId=mipfedqa
      - keycloak.client.clientSecret=492ddb7d-a7c6-4143-89ae-dbfa6f970aca
      - keycloak.client.accessTokenUri=https://iam.humanbrainproject.eu/auth/realms/MIP/protocol/openid-connect/token
      - keycloak.resource.userInfoUri=https://iam.humanbrainproject.eu/auth/realms/MIP/protocol/openid-connect/userinfo
      - keycloak.client.userAuthorizationUri=https://iam.humanbrainproject.eu/auth/realms/MIP/protocol/openid-connect/auth
      - keycloak.client.logout_uri=https://iam.humanbrainproject.eu/auth/realms/MIP/protocol/openid-connect/logout
      - keycloak.client.redirect_uri=http://localhost:4200/pathologies
    restart: on-failure


  datacatalogue_frontend:
    build: frontend
    image: angular-frontend
    ports:
      - 4200:4200
    depends_on:
      - datacatalogue_backend
    links:
      - datacatalogue_backend
    restart: on-failure


  datacatalogue_postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=datacatalog
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=password

    volumes:
      - ./postgres_data:/var/lib/postgresql/data


    restart: on-failure
