version: '3.2'
services:
  backend:
    build: ''
    image: spring-boot-backend
    expose:
      - 8086
    ports:
      - '8086:8086'
    depends_on:
      - postgres
    links:
      - postgres
    restart: on-failure
    networks:
      datalogue_net:
        ipv4_address: 172.28.1.2

  frontend:
    build: frontend
    image: angular-frontend
    expose:
      - 4200
    ports:
      - '4200:4200'
    depends_on:
      - backend
    links:
      - backend
    restart: on-failure
    networks:
      datalogue_net:
        ipv4_address: 172.28.1.3

  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=datacatalog
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=password

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    restart: on-failure
    networks:
      datalogue_net:
        ipv4_address: 172.28.1.1

#volumes:
#  db-data:

networks:
  datalogue_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
